name: Secret investigation
on:
  workflow_dispatch:
    
jobs:
  build:
    environment: development
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env: 
            HELLO_GITHUB_ACTIONS_SECRET: ${{ secrets.HELLO_GITHUB_ACTIONS_SECRET }}
        run: |
            echo "$HELLO_GITHUB_ACTIONS_SECRET"
      - shell: bash
        env: 
            SECRET_NAME: ${{ secrets.DEV }}
        run: |
            echo "$SECRET_NAME"
